apiVersion: apps/v1
kind: Deployment

metadata:
  name: jenk-trial
  labels:
    app: jenk-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: jenk-app

  template:
    metadata:
      labels:
        app: jenk-app

    spec:
      containers:
      - name: jenk-container
        image: jenk:v1

        ports:
        - containerPort: 80

        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"

          limits:
            memory: "128Mi"
            cpu: "500m"

        env:
        - name: ENVIRONMENT
          value: "production"